# Generated by Django 6.0.6 on 2026-08-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_multi_tenant_restaurant'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='restaurants.restaurant'),
        ),
    ]
