# Generated by Django 6.0.6 on 2026-08-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_code_batch_initial_quantity_batch_status'),
        ('restaurants', '0001_multi_tenant_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('reserve', 'In reserve'), ('in_service', 'In service')], default='in_service', max_length=20),
        ),
    ]
