# Generated by Django 6.0.6 on 2026-06-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='created',
            new_name='created_at',
        ),
    ]
