# Generated by Django 6.0.6 on 2026-08-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_created_alert_created_at'),
        ('restaurants', '0001_multi_tenant_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='restaurants.restaurant'),
        ),
    ]
