# Generated by Django 6.0.6 on 2026-06-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_min_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
