# Generated by Django 6.0.6 on 2026-08-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_shelf_life_days'),
        ('restaurants', '0001_multi_tenant_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('restaurant', 'name')},
        ),
    ]
