# Generated by Django 6.0.6 on 2026-08-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_multi_tenant_restaurant'),
        ('suppliers', '0004_supplier_contact_supplier_created_at_supplier_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('restaurant', 'name')},
        ),
    ]
