# Generated by Django 6.0.6 on 2026-06-16 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_alter_article_min_threshold_and_more'),
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entry', 'Entry'), ('kitchen_exit', 'Kitchen_Exit'), ('loss', 'Loss'), ('deletion', 'Deletion')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('motive', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='articles.article')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='batches.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movements',
            },
        ),
    ]
