# Generated by Django 6.0.6 on 2026-06-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('entry', 'Entry'), ('kitchen_exit', 'Kitchen_Exit'), ('loss', 'Loss'), ('deletion', 'Deletion'), ('activation', 'Activation'), ('correction', 'Correction')], max_length=20),
        ),
    ]
