# Generated by Django 6.0.6 on 2026-06-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_code_batch_initial_quantity_batch_status'),
        ('movements', '0002_alter_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='batches.batch'),
        ),
    ]
