# Generated by Django 6.0.6 on 2026-07-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0004_alter_movement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
