# Generated by Django 6.0.6 on 2026-07-09 09:41

from django.db import migrations


# WHEN/WHY: user_name is a snapshot taken at movement creation so history keeps
# the author's name after account deletion. Existing rows predate the field;
# copy the name from the still-linked user (rows whose user was already deleted
# keep '' and the UI falls back to "Système").
def backfill_user_name(apps, schema_editor):
    Movement = apps.get_model('movements', 'Movement')
    movements = list(
        Movement.objects.exclude(user__isnull=True).select_related('user')
    )
    for movement in movements:
        movement.user_name = movement.user.name
    Movement.objects.bulk_update(movements, ['user_name'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0005_movement_user_name'),
    ]

    operations = [
        migrations.RunPython(backfill_user_name, migrations.RunPython.noop),
    ]
