# Generated by Django 6.0.6 on 2026-06-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='auto_expiration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='critical_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='default_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('fefo', 'FEFO strict'), ('multi_lots', 'Multi-lots')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='soon_expires_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='switch_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
