"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

#from django.conf.global_settings import SECRET_KEY

from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

# WHEN/WHY: the mobile app (Expo) reaches Django over the LAN IP, which the
# previous empty list (localhost-only when DEBUG) rejected with a 400. The
# list now comes from .env — e.g. ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.20
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.accounts',
    'apps.categories',
    'apps.suppliers',
    'apps.articles',
    'apps.batches',
    'apps.movements',
    'apps.alerts',
    # WHEN/WHY: new app backing the frontend delivery/receiving workflow.
    'apps.deliveries',
    # WHEN/WHY: configurable branding (restaurant name) + admin maintenance (wipe).
    'apps.system',
]

# WHY: single source of truth for the default product/restaurant name. Used when
# no custom name has been set, and as the target of "restore to default". Change
# it here (or via the DEFAULT_RESTAURANT_NAME env var) to rebrand the default.
DEFAULT_RESTAURANT_NAME = os.getenv("DEFAULT_RESTAURANT_NAME", "Cuistock")

# Before any migration
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # WHEN/WHY: custom JWT auth that also enforces a single active session
        # (rejects tokens whose `sid` no longer matches the user). Replaces the
        # default 'rest_framework_simplejwt.authentication.JWTAuthentication'.
        'apps.accounts.authentication.SessionJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # WHEN/WHY: login/register had no throttling (unlimited credential guessing
    # and pending-account spam). Scoped throttles are declared on the two views
    # (throttle_scope = 'login' / 'register'); rates are tunable via env.
    'DEFAULT_THROTTLE_RATES': {
        'login': os.getenv('THROTTLE_LOGIN', '10/min'),
        'register': os.getenv('THROTTLE_REGISTER', '10/hour'),
    },
}

MIDDLEWARE = [
    # WHEN/WHY: CorsMiddleware must sit as high as possible (django-cors-headers
    # docs), before any middleware that can generate a response (CommonMiddleware
    # redirects, auth failures, ...). It used to be LAST, so early responses from
    # the middlewares above it shipped without CORS headers.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}

# Password encryption
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Authorize React
# WHEN/WHY: the frontend moved from Vite (5173) to Next.js. The Next.js dev
# server (3000) and the chosen preview port (3144) are allowed so the browser /
# adapter routes can call this API. 5173 kept for backward compatibility.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:3144",
]

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# WHEN/WHY: single-session idle window. A logged-in session is considered "live"
# only while it has been seen within this window; past it, the session frees
# itself (so closing the browser or killing the servers without logging out can
# no longer lock the account for the full 8h access-token lifetime). It also
# enforces server-side inactivity logout. The frontend uses the same value to
# auto-logout and to drive its activity heartbeat. Configurable via env.
SESSION_IDLE_TIMEOUT = timedelta(minutes=int(os.getenv("SESSION_IDLE_MINUTES", "15")))