# Generated by Django 6.0.6 on 2026-06-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_permissions_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
